In [2]:
import pandas

ceo_data = pandas.read_csv("ceo_data.csv")

ceo_data

,ranking,ceo,company,tgc,tgc_yr,trc,trc_yr,tsr,tsr_yr
0,1,"Pichai, Sundar",Alphabet Inc.,276932830,NaN,8274631,NaN,-29.0,30.0
1,2,"Ianniello, Joseph",ViacomCBS Inc.,125433673,NaN,112927969,NaN,2.0,23.0
2,3,"Testrow, Ian",Emeco Holdings Limited,71302438,5862.0,18451964,1443.0,-7.0,25.0
3,4,"Swan, Robert",Intel Corporation,66935100,326.0,12983400,31.0,-31.0,26.0
4,5,"Su, Lisa","Advanced Micro Devices, Inc.",58534288,338.0,38870577,-15.0,-148.0,69.0
5,6,"Wenig, Devin",eBay Inc.,57225870,215.0,75053893,196.0,-31.0,56.0
6,7,"Dolan, James",The Madison Square Garden Company,54116491,367.0,9727834,63.0,-10.0,-17.0
7,8,"Plant, John",Arconic Inc.,51712578,NaN,21771078,NaN,-84.0,121.0
8,9,"Ermotti, Sergio",UBS Group AG,47710452,232.0,12032252,-3.0,-5.0,34.0
9,10,"Iger, Robert",The Walt Disney Company,47517762,-28.0,67918815,3.0,-34.0,30.0
10,11,"Silbermann, Benjamin","Pinterest, Inc.",46222113,NaN,32996177,NaN,NaN,NaN
11,12,"Zaslav, David","Discovery Communications, Inc.",45843912,-65.0,50646901,51.0,-32.0,22.0
12,13,"Maffei, Gregory",Liberty Media Corporation,44045070,119.0,152676239,1548.0,NaN,NaN
13,14,"Patricio, Miguel",The Kraft Heinz Company,43297480,NaN,2551285,NaN,21.0,21.0
14,15,"Nadella, Satya",Microsoft Corporation,42910215,66.0,191751389,450.0,-58.0,37.0
15,16,"Gelsinger, Patrick","VMware, Inc.",42549725,81.0,81690281,132.0,-11.0,-21.0
16,17,"Khosrowshahi, Dara","Uber Technologies, Inc.",42428233,-6.0,37069227,613.0,NaN,NaN
17,18,"Schneider, David",Zalando SE,42216784,341.0,86609,-99.0,-101.0,150.0
18,19,"Ritter, Rubin",Zalando SE,42216168,341.0,7604822,44.0,-101.0,150.0
19,20,"Gentz, Robert",Zalando SE,42215267,341.0,85091,-99.0,-101.0,150.0
20,21,"McDermott, William","ServiceNow, Inc.",41682335,NaN,1873259,NaN,-59.0,22.0
21,22,"Narayen, Shantanu",Adobe Systems Incorporated,39145631,38.0,69396442,3.0,-46.0,17.0
22,23,"Hastings, Wilmot","Netflix, Inc.",38577129,7.0,222643547,5377.0,-21.0,-19.0
23,24,"Merlo, Larry",CVS Health Corporation,36451749,66.0,29294021,89.0,-17.0,24.0
24,25,"Simon, Irwin","The Hain Celestial Group, Inc.",36373053,387.0,40864186,218.0,-64.0,126.0
25,26,"Roberts, Brian",Comcast Corporation,36370183,4.0,144283880,204.0,-34.0,47.0
26,27,"Umpleby, D.",Caterpillar Inc.,34519129,26.0,26294681,77.0,-20.0,37.0
27,28,"Wirth, Michael",Chevron Corporation,33070662,60.0,24485657,34.0,-15.0,25.0
28,29,"Manley, Michael",Fiat Chrysler Automobiles N.V.,32595999,628.0,8153251,451.0,-21.0,36.0
29,30,"Gabelli, Mario","GAMCO Investors, Inc.",32236004,202.0,43269324,306.0,-16.0,59.0
30,31,"Niccol, Brian","Chipotle Mexican Grill, Inc.",32136288,-4.0,42205599,714.0,-94.0,44.0
31,32,"Stephenson, Randall",AT&T Inc.,32032925,10.0,27727298,28.0,-46.0,68.0
32,33,"Garland, Greg",Phillips 66,31900878,65.0,54470121,113.0,-34.0,46.0
33,34,"Gorman, James",Morgan Stanley,31642395,12.0,23433106,21.0,-33.0,55.0
34,35,"Dimon, James",JPMorgan Chase & Co.,31612616,5.0,107815980,494.0,-47.0,54.0
35,36,"O’Sullivan, Michael","Burlington Stores, Inc.",31056597,NaN,769161,NaN,-40.0,8.0
36,37,"Moghadam, Hamid","Prologis, Inc.",30383438,8.0,27002215,-25.0,-56.0,62.0
37,38,"Lance, Ryan",ConocoPhillips,30363744,30.0,53848638,146.0,-7.0,-9.0
38,39,"Ossip, David",Ceridian HCM Holding Inc.,30180957,159.0,43917997,2744.0,-97.0,NaN
39,40,"Kotick, Robert","Activision Blizzard, Inc.",30122896,-2.0,43740349,915.0,-29.0,55.0
40,41,"Narasimhan, Laxman",Reckitt Benckiser Group plc,29507921,NaN,5697155,NaN,-5.0,16.0
41,42,"Scharf, Charles",Wells Fargo & Company,29286574,NaN,503130,NaN,-21.0,43.0
42,43,"Gorder, Joseph",Valero Energy Corporation,28200511,50.0,20481316,-36.0,-30.0,46.0
43,44,"Fanning, Thomas",The Southern Company,27865185,113.0,78174160,809.0,-52.0,55.0
44,45,"White, Miles",Abbott Laboratories,27802817,15.0,53812462,70.0,-22.0,-7.0
45,46,"Legere, John","T-Mobile US, Inc.",27756690,-58.0,32833829,-22.0,-23.0,23.0
46,47,"Charlès, Bernard",Dassault Systèmes SE,27754879,6.0,3363677,-95.0,-42.0,24.0
47,48,"Norcross, Gary","Fidelity National Information Services, Inc.",27658117,50.0,43776767,24.0,-37.0,27.0
48,49,"Frazier, Kenneth","Merck & Co., Inc.",27648475,32.0,55609124,14.0,-22.0,-18.0
49,50,"Yabuki, Jeffery","Fiserv, Inc.",27601026,122.0,108542760,42.0,-57.0,45.0